openapi: 3.0.0
info:
  title: MY SWEET SKRIPSI
  contact: {}
  version: "1.0.0"
servers:
  - url: http://localhost:8000/v1/api
  - url: https://be-permission.up.railway.app/v1/api
    variables: {}

paths:
  #FOR USERS LOGIN AND DASHBOARD
  /login:
    post:
      tags:
        - For Dashboard
      summary: LOGIN PAGE
      description: ""
      operationId: LOGINPAGE
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: "hendripermana60@gmail.com"
                password:
                  type: string
                  description: "User's password"
              required:
                - email
                - password
            examples:
              example1:
                value:
                  email: "hendripermana60@gmail.com"
                  password: "12345"
      responses:
        "200":
          description: Successful response
          headers: {}
          content: {}
        "400":
          description: Login Not Successed
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
  /logout:
    delete:
      tags:
        - For Dashboard
      summary: LOGOUT
      description: ""
      operationId: LOGOUT
      parameters: []
      responses:
        "200":
          description: Successful response
          headers: {}
          content: {}
        "400":
          description: Already Logout
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /me:
    get:
      tags:
        - For Dashboard
      summary: GET USER DETAIL
      description: ""
      operationId: USERDETAIL
      parameters: []
      responses:
        "200":
          description: Successful response
          headers: {}
          content: {}
        "400":
          description: No Users Found
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /dashboard:
    get:
      tags:
        - For Dashboard
      summary: GET DATA DASHBOARD
      description: ""
      operationId: GETDATADASHBOARD
      parameters: []
      responses:
        "200":
          description: Successful Get Data Dashboard
          headers: {}
          content: {}
        "400":
          description: No Data Found
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []

  #FOR DATA PROVINCE
  /province:
    get:
      tags:
        - For Data Province
      summary: GET ALL DATA PROVINCE ALL
      description: ""
      operationId: GETDATAPROVINCEALL
      parameters: []
      responses:
        "200":
          description: Successful Get data province
          headers: {}
          content: {}
        "400":
          description: Error or not Success get data province
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /province/byid/{id}:
    get:
      tags:
        - For Data Province
      summary: GET DATA PROVINCE BY ID
      description: ""
      operationId: GETDATAPROVINCEBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful Get data province
          headers: {}
          content: {}
        "400":
          description: Error or not Success get data province
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /province/{search}:
    get:
      tags:
        - For Data Province
      summary: GET DATA PROVINCE BY NAME
      description: ""
      operationId: GETDATAPROVINCEBYNAME
      parameters:
        - name: search
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful Get data province by name
          headers: {}
          content: {}
        "400":
          description: Error or not Success get data province by name
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /province/register:
    post:
      tags:
        - For Data Province
      summary: REGISTER DATA PROVINCE
      description: ""
      operationId: CREATEPROVINCEDATA
      parameters: []
      requestBody:
        description: ""
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name_province:
                  type: string
                  description: Insert Name Santri
                sex:
                  type: integer
                  description: 1 for Men, 0 for Women
                fathername:
                  type: string
                  description: Father Name Insert
                mothername:
                  type: string
                  description: Mother Name Insert
                id_room:
                  type: integer
                  description: Where Santri/Santriwati is living
                image:
                  type: string
                  format: binary
                  description: Upload image for Santri/Wati
              required:
                - name_province
                - sex
                - fathername
                - mothername
                - id_room
                - image
            examples:
              example1:
                value:
                  name_province: "Hendri Permana Putra"
                  sex: 1
                  fathername: "Ayah Hendri"
                  mothername: "Ibu Hendri"
                  id_room: 1
                  image: ""
      responses:
        "200":
          description: Successful create data province
          headers: {}
          content: {}
        "400":
          description: Error or not success create data province
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /province/update/{id}:
    put:
      tags:
        - For Data Province
      summary: UPDATE DATA PROVINCE BY ID
      description: ""
      operationId: UPDATEDATAPROVINCEBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: ""
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name_province:
                  type: string
                  description: Insert Name Santri
                sex:
                  type: integer
                  description: 1 for Men, 0 for Women
                fathername:
                  type: string
                  description: Father Name Insert
                mothername:
                  type: string
                  description: Mother Name Insert
                id_room:
                  type: integer
                  description: Where Santri/Santriwati is living
                image:
                  type: string
                  format: binary
                  description: Upload image for Santri/Wati
              required:
                - name_province
                - sex
                - fathername
                - mothername
                - id_room
                - image
            examples:
              example1:
                value:
                  name_province: "Hendri Permana Putra"
                  sex: 1
                  fathername: "Ayah Hendri"
                  mothername: "Ibu Hendri"
                  id_room: 1
                  image: ""
        required: false
      responses:
        "200":
          description: Successful update data province by id
          headers: {}
          content: {}
        "400":
          description: Error or not success update data province by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /province/delete/{id}:
    delete:
      tags:
        - For Data Province
      summary: DELETE DATA STUDENT
      description: ""
      operationId: DELETEDATASTUDENTBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful delete data province
          headers: {}
          content: {}
        "400":
          description: Error or not success delete data province
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []

  #FOR DATA PEGAWAI
  /users:
    get:
      tags:
        - For Data Users
      summary: GET DATA PEGAWAI ALL
      description: ""
      operationId: GETDATAPEGAWAIALL
      parameters: []
      responses:
        "200":
          description: Successful Get data pegawai
          headers: {}
          content: {}
        "400":
          description: Error or not Success get data pegawai
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /users/byid/{id}:
    get:
      tags:
        - For Data Users
      summary: GET DATA PEGAWAI BY ID
      description: ""
      operationId: GETDATAPEGAWAIBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful Get data pegawai by id
          headers: {}
          content: {}
        "400":
          description: Error or not Success get data pegawai by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /users/{search}:
    get:
      tags:
        - For Data Users
      summary: GET DATA PEGAWAI BY SEARCH
      description: ""
      operationId: GETDATAPEGAWAIBYSEARCH
      parameters:
        - name: search
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful Get data pegawai by search name
          headers: {}
          content: {}
        "400":
          description: Error or not Success get data pegawai by search name
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /users/delete/{id}:
    delete:
      tags:
        - For Data Users
      summary: DELETE PEGAWAI BY ID
      description: ""
      operationId: DELETEPEGAWAIBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful delete data pegawai by id
          headers: {}
          content: {}
        "400":
          description: Error or not Success delete data pegawai by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /users/register:
    post:
      tags:
        - For Data Users
      summary: REGISTER PEGAWAI
      description: ""
      operationId: REGISTERPEGAWAI
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                name_pegawai:
                  type: string
                  description: "insert name"
                sex:
                  type: integer
                  description: "1 for men, and 0 for women"
                email:
                  type: string
                  format: email
                  description: "insert name"
                password:
                  type: string
                  description: "insert password"
                role_id:
                  type: integer
                  description: "choose your role, 1. admin, 2. ustadz, 3. security"
              required:
                - name_pegawai
                - sex
                - email
                - password
                - role_id
            examples:
              example1:
                value:
                  name_pegawai: "Hendri Edited"
                  sex: 1
                  email: "hendripermana60@gmail.com123"
                  password: "12345cekceksaja"
                  role_id: 2
      responses:
        "200":
          description: Successful create data pegawai
          headers: {}
          content: {}
        "400":
          description: Error or not success create data pegawai
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /users/update/{id}:
    put:
      tags:
        - For Data Users
      summary: UPDATE DATA PEGAWAI BY ID
      description: ""
      operationId: UPDATEDATAPEGAWAIBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                name_pegawai:
                  type: string
                  description: "insert name"
                sex:
                  type: integer
                  description: "1 for men, and 0 for women"
                email:
                  type: string
                  format: email
                  description: "insert name"
                password:
                  type: string
                  description: "insert password"
                role_id:
                  type: integer
                  description: "choose your role, 1. admin, 2. ustadz, 3. security"
              required:
                - name_pegawai
                - sex
                - email
                - password
                - role_id
            examples:
              example1:
                value:
                  name_pegawai: "Hendri Edited"
                  sex: 1
                  email: "hendripermana60@gmail.com123"
                  password: "12345cekceksaja"
                  role_id: 2
        required: false
      responses:
        "200":
          description: Successful update data pegawai by id
          headers: {}
          content: {}
        "400":
          description: Error or not success update data pegawai by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []

  #FOR DATA KRITERIA & SUBKRITERIA
  /kriteria:
    get:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: GET DATA KRITERIA AND SUB-KRITERIA ALL
      description: ""
      operationId: GETDATAKRITERIAALL
      parameters: []
      responses:
        "200":
          description: Successful Get data kriteria
          headers: {}
          content: {}
        "400":
          description: Error or not success get data kriteria
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /kriteria/byid/{id}:
    get:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: GET DATA KRITERIA BY ID
      description: ""
      operationId: GETDATAKRITERIABYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful Get data kriteria by id
          headers: {}
          content: {}
        "400":
          description: Error or not success get data kriteria by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /kriteria/update/{id}:
    put:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: UPDATE DATA KRITERIA BY ID
      description: ""
      operationId: UPDATEDATAKRITERIABYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                scale_priority:
                  type: integer
                  description: "Skala Prioritas"
                name_kriteria:
                  type: string
                  description: "Name kriteria"
                type:
                  type: integer
                  description: "1 Benefit, 2 cost"
                subkriteria:
                  type: string
                  description: "Sub Kriteria array input"
              required:
                - scale_priority
                - name_kriteria
                - type
                - subkriteria
            examples:
              example1:
                value:
                  scale_priority: 3
                  name_kriteria: "Edited Kriteria"
                  type: 1
                  subkriteria:
                    [
                      { name_sub: "subkriteria-1", value: 1 },
                      { name_sub: "subkriteria-2", value: 2 },
                      { name_sub: "subkriteria-3", value: 3 },
                    ]
        required: false
      responses:
        "200":
          description: Successful update data kriteria by id
          headers: {}
          content: {}
        "400":
          description: Error or not success update data kriteria by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /kriteria/delete/{id}:
    delete:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: DELETE KRITERIA AND SUB-KRITERIA BY ID
      description: ""
      operationId: DELETEKRITERIABYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful delete data kriteria by id
          headers: {}
          content: {}
        "400":
          description: Error or not success delete data kriteria by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /kriteria/create:
    post:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: REGISTER KRITERIA AND SUB-KRITERIA
      description: ""
      operationId: REGISTERKRITERIAANDSUBKRITERIA
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                scale_priority:
                  type: integer
                  description: "Skala Prioritas"
                name_kriteria:
                  type: string
                  description: "Name kriteria"
                type:
                  type: integer
                  description: "1 Benefit, 2 cost"
                subkriteria:
                  type: string
                  description: "Sub Kriteria array input"
              required:
                - scale_priority
                - name_kriteria
                - type
                - subkriteria
            examples:
              example1:
                value:
                  scale_priority: 3
                  name_kriteria: "Edited Kriteria"
                  type: 1
                  subkriteria:
                    [
                      { name_sub: "subkriteria-1", value: 1 },
                      { name_sub: "subkriteria-2", value: 2 },
                      { name_sub: "subkriteria-3", value: 3 },
                    ]
        required: false
      responses:
        "200":
          description: Successful create data kriteria
          headers: {}
          content: {}
        "400":
          description: Error or not success create data kriteria by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: fal se
      security:
        - bearerAuth: []

  #FOR PROGRAMS
  /program:
    get:
      tags:
        - For Data Program
      summary: GET DATA KRITERIA AND SUB-KRITERIA ALL
      description: ""
      operationId: GETDATAKRITERIAALL
      parameters: []
      responses:
        "200":
          description: Successful Get data kriteria
          headers: {}
          content: {}
        "400":
          description: Error or not success get data kriteria
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /program/byid/{id}:
    get:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: GET DATA KRITERIA BY ID
      description: ""
      operationId: GETDATAKRITERIABYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful Get data kriteria by id
          headers: {}
          content: {}
        "400":
          description: Error or not success get data kriteria by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /program/update/{id}:
    put:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: UPDATE DATA KRITERIA BY ID
      description: ""
      operationId: UPDATEDATAKRITERIABYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                scale_priority:
                  type: integer
                  description: "Skala Prioritas"
                name_kriteria:
                  type: string
                  description: "Name kriteria"
                type:
                  type: integer
                  description: "1 Benefit, 2 cost"
                subkriteria:
                  type: string
                  description: "Sub Kriteria array input"
              required:
                - scale_priority
                - name_kriteria
                - type
                - subkriteria
            examples:
              example1:
                value:
                  scale_priority: 3
                  name_kriteria: "Edited Kriteria"
                  type: 1
                  subkriteria:
                    [
                      { name_sub: "subkriteria-1", value: 1 },
                      { name_sub: "subkriteria-2", value: 2 },
                      { name_sub: "subkriteria-3", value: 3 },
                    ]
        required: false
      responses:
        "200":
          description: Successful update data kriteria by id
          headers: {}
          content: {}
        "400":
          description: Error or not success update data kriteria by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /program/delete/{id}:
    delete:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: DELETE KRITERIA AND SUB-KRITERIA BY ID
      description: ""
      operationId: DELETEKRITERIABYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful delete data kriteria by id
          headers: {}
          content: {}
        "400":
          description: Error or not success delete data kriteria by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /program/create:
    post:
      tags:
        - For Data Kriteria and Sub-kriteria
      summary: REGISTER KRITERIA AND SUB-KRITERIA
      description: ""
      operationId: REGISTERKRITERIAANDSUBKRITERIA
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                scale_priority:
                  type: integer
                  description: "Skala Prioritas"
                name_kriteria:
                  type: string
                  description: "Name kriteria"
                type:
                  type: integer
                  description: "1 Benefit, 2 cost"
                subkriteria:
                  type: string
                  description: "Sub Kriteria array input"
              required:
                - scale_priority
                - name_kriteria
                - type
                - subkriteria
            examples:
              example1:
                value:
                  scale_priority: 3
                  name_kriteria: "Edited Kriteria"
                  type: 1
                  subkriteria:
                    [
                      { name_sub: "subkriteria-1", value: 1 },
                      { name_sub: "subkriteria-2", value: 2 },
                      { name_sub: "subkriteria-3", value: 3 },
                    ]
        required: false
      responses:
        "200":
          description: Successful create data kriteria
          headers: {}
          content: {}
        "400":
          description: Error or not success create data kriteria by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []

  #FOR DATA AJUAN
  /ajuan/all:
    get:
      tags:
        - For Data Ajuan
      summary: GET DATA AJUAN ALL
      description: ""
      operationId: GETDATAAJUANALL
      parameters: []
      responses:
        "200":
          description: Successful get data permission
          headers: {}
          content: {}
        "400":
          description: Error or not success get data permission
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /ajuan/byid/{id}:
    get:
      tags:
        - For Data Ajuan
      summary: GET DATA AJUAN BY ID
      description: ""
      operationId: GETDATAAJUANBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful get data permission by id
          headers: {}
          content: {}
        "400":
          description: Error or not success get data permission by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /ajuan:
    get:
      tags:
        - For Data Ajuan
      summary: GET DATA AJUAN BY CREATED
      description: ""
      operationId: GETDATAAJUANBYCREATED
      parameters: []
      responses:
        "200":
          description: Successful get data permission by created
          headers: {}
          content: {}
        "400":
          description: Error or not success get data permission by created
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /ajuan/delete/{id}:
    delete:
      tags:
        - For Data Ajuan
      summary: DELETE AJUAN BY ID
      description: ""
      operationId: DELETEAJUANBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful delete data permission by id
          headers: {}
          content: {}
        "400":
          description: Error or not success delete data permission
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /ajuan/create:
    post:
      tags:
        - For Data Ajuan
      summary: CREATED AJUAN
      description: ""
      operationId: CREATEDAJUAN
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                student_id:
                  type: integer
                  description: "Skala Prioritas"
                start_permission:
                  type: string
                  format: date
                  description: "Start Ajuan Date"
                end_permission:
                  type: string
                  format: date
                  description: "End Ajuan Date"
                commented:
                  type: string
                  description: "Sub Kriteria array input"
                kriteria:
                  type: string
                  description: "kriteria input"
              required:
                - student_id
                - start_permission
                - end_permission
                - commented
                - kriteria
            examples:
              example1:
                value:
                  student_id: 1
                  start_permission: 2024-02-05 12:24:23
                  end_permission: 2024-02-10 13:24:23
                  commented: "Sakit karena demam"
                  kriteria:
                    [
                      { id_kriteria: 1, id_subkriteria: 2 },
                      { id_kriteria: 2, id_subkriteria: 6 },
                      { id_kriteria: 3, id_subkriteria: 17 },
                    ]
        required: false
      responses:
        "200":
          description: Successful create data permission
          headers: {}
          content: {}
        "400":
          description: Error or not success create data permission
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /ajuan/update/{id}:
    put:
      tags:
        - For Data Ajuan
      summary: UPDATE DATA AJUAN BY ID
      description: ""
      operationId: UPDATEDATAAJUANBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
              properties:
                student_id:
                  type: integer
                  description: "Skala Prioritas"
                start_permission:
                  type: string
                  format: date
                  description: "Start Ajuan Date"
                end_permission:
                  type: string
                  format: date
                  description: "End Ajuan Date"
                commented:
                  type: string
                  description: "Sub Kriteria array input"
                kriteria:
                  type: string
                  description: "kriteria input"
              required:
                - student_id
                - start_permission
                - end_permission
                - commented
                - kriteria
            examples:
              example1:
                value:
                  student_id: 1
                  start_permission: 2024-02-05 12:24:23
                  end_permission: 2024-02-10 13:24:23
                  commented: "Sakit karena demam"
                  kriteria:
                    [
                      { id_kriteria: 1, id_subkriteria: 2 },
                      { id_kriteria: 2, id_subkriteria: 6 },
                      { id_kriteria: 3, id_subkriteria: 17 },
                    ]
        required: false
      responses:
        "200":
          description: Successful update data permission by id
          headers: {}
          content: {}
        "400":
          description: Error or not success update data permission by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []

  /action/calculatedPSI:
    post:
      tags:
        - For Calculated
      summary: CALCULATED PSI
      description: ""
      operationId: CALCULATEDPSI
      parameters: []
      responses:
        "200":
          description: Successful calculated PSI
          headers: {}
          content: {}
        "400":
          description: Error or not success calculated PSI
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /result/PSI/{id}:
    get:
      tags:
        - For Calculated
      summary: GET RESULT PSI BY ID
      description: ""
      operationId: GETRESULTROCANDPSIBYID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful get calculated ROC & PSI by id
          headers: {}
          content: {}
        "400":
          description: Error or not success get calculated ROC & PSI by id
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []
  /datareqByUser:
    get:
      tags:
        - For Calculated
      summary: Get Data Req By User
      description: ""
      operationId: GETDATAUSERREQ
      parameters: []
      responses:
        "200":
          description: Successful Get Data Req User by Created
          headers: {}
          content: {}
        "400":
          description: Error or not success get Data Req User by Created
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []

  #FOR REPORT
  /report:
    get:
      tags:
        - For Report
      summary: GET DATA FOR REPORT
      description: ""
      operationId: REPORTDATA
      parameters: []
      responses:
        "200":
          description: Successful get report
          headers: {}
          content: {}
        "400":
          description: Error or not success get report
          headers: {}
          content: {}
        "500":
          description: internal server error
          headers: {}
          content: {}
      deprecated: false
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security: []
tags:
  - name: For Dashboard
    description: Endpoint beginning
  - name: For Data Province
    description: This API for handler Data Santri/ Wati
  - name: For Data Users
    description: This API For Handler Data Users
  - name: For Data Kriteria and Sub-kriteria
    description: This API For Handler Kriteria
  - name: For Data Requests Proposal
    description: This API For Handler Requests Proposal
  - name: For Report
    description: This API For Handler Report
  - name: For Calculated
    description: This API For Handler Calculate ROC and PSI
